name: Complete CI Workflow

on:
  pull_request:
    branches:
      - main
      - 'releases/**'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout greeter repository
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.8"
      - name: Check for scalafmt conformance
        uses: jrouly/scalafmt-native-action@v1
        with:
          version: '3.0.0'
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and Test
        run: sbt -v -Dfile.encoding=UTF-8 +test
